# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - newwebappXYZ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://myacrdemoxyz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e05833891b994401bee458d09cec2b84 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6e0fdeb42a164df4b3a2860d1992f35f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: myacrdemoxyz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e05833891b994401bee458d09cec2b84 }}/imageFINAL:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'newwebappXYZ'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_013ab584d9104b8faad393c9aeb7060b }}
        images: 'myacrdemoxyz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e05833891b994401bee458d09cec2b84 }}/imageFINAL:${{ github.sha }}'